### ISSUE TITLE
production.py BASE_DIR varaible error

### ISSUE THREAD

**Issue by SergeyDubovitsky** [bobbyrussell/django-skeleton-1.8#1]
line 29: 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

**Comment by bobbyrussell** [comment]
https://github.com/bobbyrussell

**Comment by bobbyrussell** [comment]
This fixed the issue:
https://github.com/bobbyrussell/django-skeleton-1.8/commit/c290e506af4cecc1abe73738ff71efb52572a00a

Closing this now. Thanks for reporting it!
